version: "3.9"

services:
  php:
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
    container_name: micro-mvc-php-container
    volumes:
      - ./:/var/www/html/:cached
    networks:
      - micro-mvc-net

  nginx:
    build:
      context: ./docker
      dockerfile: ./nginx/Dockerfile
    container_name: micro-mvc-nginx-container
    volumes:
      - ./:/var/www/html/:cached
    ports:
      - "10320:80"
    networks:
      - micro-mvc-net
    depends_on:
      - database
      - php

  database:
    image: mariadb:10.6.7
    container_name: micro-mvc-db-container
    ports:
      - "3366:3306"
    # restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - persistent:/var/lib/mysql
    networks:
    - micro-mvc-net

networks:
  micro-mvc-net:

volumes:
  persistent:
